# Site settings
title: My Portfolio
email: lshopowa@gmail.com
description: This is a website about my design works and contains my front-end projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lorams.github.io/" 
github_username:  LoraMS
lang: en 
languages: ["en", "bg"] 

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Languages settings
defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"
      layout: default
  -
    scope:
      path: "bg"
    values:
      lang: "bg"


# Translation
t:
  en:
    home:
      name: "Home"
      url: "/"
    about:
      name: "About"
      url: "/about"
    education:
      name: "Education"
      url: "/education"
    certificates:
      name: "Certificates"
      url: "/certificates"
    projects:
      name: "Projects"
      url: "/projects"
    contact:
      name: "Contacts"
      url: "/contacts"
  bg:
    home:
      name: "Начало"
      url: "/index_bg"
    about:
      name: "За мен"
      url: "/about_bg"
    education:
      name: "Образование"
      url: "/education_bg"
    certificates:
      name: "Сертификати"
      url: "/certificates_bg"
    projects:
      name: "Проекти"
      url: "/projects_bg"
    contact:
      name: "Контакти"
      url: "/contacts_bg"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
